Christmas tree
rafprzygoda/9.4_loops pull request #1
Opened 2017-06-02 19:54 UTC by rafprzygoda

Hi, 
I tried to add second loop but I give up. Even Google not help. This kind of code is simpliest.

2017-06-03 08:30 UTC, matwjablonski requested changes

2017-06-03 08:30 UTC, matwjablonski commented on js/scripts.js
> +
remove unnecessary empty lines

2017-06-03 11:59 UTC, rafprzygoda commented
I deleted spaces.

2017-06-04 09:48 UTC, matwjablonski approved these changes

2017-06-17 20:24 UTC, merged